/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';


export interface Address { 
    id?: number;
    userId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1: string;
    addressLine2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
    phoneNumber?: string | null;
    email?: string | null;
    addressName?: string | null;
    isDefault?: boolean;
    createdAt?: string;
    updatedAt?: string | null;
    user?: ApplicationUser;
}

