/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDto } from './addressDto';


export interface AddressDtoIEnumerableResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<AddressDto> | null;
    timestamp?: string;
    statusCode?: number;
}

