/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { QuoteRequest } from './quoteRequest';
import { CouponUsage } from './couponUsage';
import { Review } from './review';
import { Seller } from './seller';


export interface ApplicationUser { 
    id?: string | null;
    userName?: string | null;
    normalizedUserName?: string | null;
    email?: string | null;
    normalizedEmail?: string | null;
    emailConfirmed?: boolean;
    passwordHash?: string | null;
    securityStamp?: string | null;
    concurrencyStamp?: string | null;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    twoFactorEnabled?: boolean;
    lockoutEnd?: string | null;
    lockoutEnabled?: boolean;
    accessFailedCount?: number;
    firstName?: string | null;
    lastName?: string | null;
    profilePictureUrl?: string | null;
    dateOfBirth?: string | null;
    gender?: string | null;
    isActive?: boolean;
    createdAt?: string;
    lastLoginAt?: string | null;
    sellerEntityId?: number | null;
    seller?: Seller;
    reviews?: Array<Review> | null;
    couponUsages?: Array<CouponUsage> | null;
    orders?: Array<Order> | null;
    quoteRequests?: Array<QuoteRequest> | null;
}

