/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDtoPaginatedList } from './articleDtoPaginatedList';


export interface ArticleDtoPaginatedListResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: ArticleDtoPaginatedList;
    timestamp?: string;
    statusCode?: number;
}

