/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ArticleTagDto { 
    id?: number;
    name?: string | null;
    slug?: string | null;
    description?: string | null;
    createdAt?: string;
}

