/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface ArticleDtoIEnumerableResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<ArticleDto> | null;
    timestamp?: string;
    statusCode?: number;
}

