/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';
import { ProductAttributeValue } from './productAttributeValue';


export interface AttributeValue { 
    id?: number;
    attributeId?: number;
    attribute?: Attribute;
    value: string;
    displayValue?: string | null;
    sortOrder?: number;
    isActive?: boolean;
    createdAt?: string;
    productAttributeValues?: Array<ProductAttributeValue> | null;
}

