/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BannerDto } from './bannerDto';


export interface BannerDtoIEnumerableResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<BannerDto> | null;
    timestamp?: string;
    statusCode?: number;
}

