/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BestSellingProductDto { 
    productId?: number;
    productName?: string | null;
    quantitySold?: number;
    revenueGenerated?: number;
}

