/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BrandStatsDto { 
    brandId?: number;
    brandName?: string | null;
    productCount?: number;
    orderCount?: number;
    revenue?: number;
}

