/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrandDto } from './brandDto';


export interface BrandDtoIEnumerableResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<BrandDto> | null;
    timestamp?: string;
    statusCode?: number;
}

