/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartDto } from './cartDto';


export interface CartDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: CartDto;
    timestamp?: string;
    statusCode?: number;
}

