/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartItemDto } from './cartItemDto';


export interface CartDto { 
    id?: number;
    userId?: string | null;
    itemCount?: number;
    subtotal?: number;
    taxAmount?: number;
    totalAmount?: number;
    items?: Array<CartItemDto> | null;
}

