/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CartCountDto } from './cartCountDto';


export interface CartCountDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: CartCountDto;
    timestamp?: string;
    statusCode?: number;
}

