/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryDto } from './categoryDto';


export interface CategoryDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: CategoryDto;
    timestamp?: string;
    statusCode?: number;
}

