/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Category } from './category';
import { Attribute } from './attribute';


export interface CategoryAttribute { 
    id?: number;
    category?: Category;
    attributeId?: number;
    attribute?: Attribute;
    isRequired?: boolean;
    isFilterable?: boolean;
    sortOrder?: number;
    createdAt?: string;
}

