/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CategoryDto { 
    id?: number;
    name: string;
    description?: string | null;
    slug?: string | null;
    imageUrl?: string | null;
    parentId?: number | null;
    parentName?: string | null;
    level?: number;
    sortOrder?: number;
    isActive?: boolean;
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKeywords?: string | null;
    createdAt?: string;
    activeProductsCount?: number;
    children?: Array<CategoryDto> | null;
}

