/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CouponUsage } from './couponUsage';


export interface Coupon { 
    id?: number;
    code: string;
    name: string;
    description?: string | null;
    couponType?: number;
    value?: number;
    minimumOrderAmount?: number | null;
    maximumDiscountAmount?: number | null;
    usageLimit?: number | null;
    usageLimitPerUser?: number | null;
    startDate?: string | null;
    endDate?: string | null;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string | null;
    usages?: Array<CouponUsage> | null;
}

