/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateProductDto { 
    name: string;
    description?: string | null;
    shortDescription?: string | null;
    price: number;
    salePrice?: number | null;
    sku?: string | null;
    barcode?: string | null;
    stockQuantity?: number;
    brandId?: number;
    categoryId?: number | null;
    supplierId?: number | null;
    sortOrder?: number;
    isActive?: boolean;
    isFeatured?: boolean;
    isNew?: boolean;
    metaTitle?: string | null;
    metaDescription?: string | null;
    metaKeywords?: string | null;
    slug?: string | null;
    tagIds?: Array<number> | null;
    specificationValues?: { [key: string]: string | null; } | null;
    images?: Array<Blob> | null;
}

