/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreateOrderItemDto } from './createOrderItemDto';
import { CreateAddressDto } from './createAddressDto';


export interface CreateOrderDto { 
    billingAddressId?: number | null;
    shippingAddressId?: number | null;
    newBillingAddress?: CreateAddressDto;
    newShippingAddress?: CreateAddressDto;
    useDefaultAddresses?: boolean;
    paymentMethodId?: number | null;
    shippingMethodId?: number | null;
    discountAmount?: number;
    shippingCost?: number;
    couponCode?: string | null;
    orderItems?: Array<CreateOrderItemDto> | null;
    notes?: string | null;
}

