/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateQuoteRequestDto { 
    customerName: string;
    customerEmail: string;
    customerPhone?: string | null;
    companyName?: string | null;
    productId?: number;
    quantity?: number;
    specialRequirements?: string | null;
}

