/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateVnPayPaymentDto { 
    amount: number;
    orderId: string;
    orderDescription?: string | null;
    orderType?: string | null;
    name?: string | null;
    email?: string | null;
    phoneNumber?: string | null;
    address?: string | null;
    locale?: string | null;
    returnUrl?: string | null;
}

