/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateArticleDto { 
    title: string;
    summary?: string | null;
    content: string;
    slug?: string | null;
    seoTitle?: string | null;
    seoDescription?: string | null;
    seoKeywords?: string | null;
    imageUrl?: string | null;
    articleType?: string | null;
    status?: string | null;
    isFeatured?: boolean;
    allowComments?: boolean;
    tagIds?: Array<number> | null;
    categoryIds?: Array<number> | null;
}

