/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BrandStatsDto } from './brandStatsDto';
import { RecentOrderDto } from './recentOrderDto';
import { BestSellingProductDto } from './bestSellingProductDto';


export interface DashboardStatsDto { 
    totalProducts?: number;
    totalOrders?: number;
    totalCustomers?: number;
    totalBrands?: number;
    totalRevenue?: number;
    totalPendingOrders?: number;
    totalActiveBanners?: number;
    todayRevenue?: number;
    todayOrders?: number;
    todayCustomers?: number;
    recentOrders?: Array<RecentOrderDto> | null;
    bestSellingProducts?: Array<BestSellingProductDto> | null;
    topBrands?: Array<BrandStatsDto> | null;
}

