/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileUploadResponse } from './fileUploadResponse';


export interface FileUploadResponseResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: FileUploadResponse;
    timestamp?: string;
    statusCode?: number;
}

