/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileProcessingTaskResponsePagedResponse } from './fileProcessingTaskResponsePagedResponse';


export interface FileProcessingTaskResponsePagedResponseResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: FileProcessingTaskResponsePagedResponse;
    timestamp?: string;
    statusCode?: number;
}

