/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileUploadResponse { 
    taskId?: string | null;
    fileName?: string | null;
    fileSize?: number;
    status?: string | null;
    message?: string | null;
}

