/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileProcessingStatusResponse { 
    taskId?: string | null;
    fileName?: string | null;
    status?: string | null;
    progress?: number;
    message?: string | null;
    outputFilePath?: string | null;
    createdAt?: string;
    startedAt?: string | null;
    completedAt?: string | null;
    errorMessage?: string | null;
}

