/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileProcessingStatistics } from './fileProcessingStatistics';


export interface FileProcessingStatisticsResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: FileProcessingStatistics;
    timestamp?: string;
    statusCode?: number;
}

