/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileProcessingStatistics { 
    totalTasks?: number;
    pendingTasks?: number;
    queuedTasks?: number;
    processingTasks?: number;
    completedTasks?: number;
    failedTasks?: number;
    cancelledTasks?: number;
    totalBytesProcessed?: number;
}

