/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface OrderStatus { 
    id?: number;
    name?: string | null;
    description?: string | null;
    orders?: Array<Order> | null;
}

