/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { ShippingMethod } from './shippingMethod';
import { OrderStatus } from './orderStatus';
import { Payment } from './payment';
import { Address } from './address';
import { OrderItem } from './orderItem';
import { PaymentMethod } from './paymentMethod';


export interface Order { 
    id?: number;
    userId: string;
    user?: ApplicationUser;
    orderNumber: string;
    orderStatusId?: number;
    orderStatus?: OrderStatus;
    subtotal?: number;
    taxAmount?: number;
    shippingCost?: number;
    discountAmount?: number;
    totalAmount?: number;
    paymentMethodId?: number | null;
    paymentMethod?: PaymentMethod;
    shippingMethodId?: number;
    shippingMethod?: ShippingMethod;
    billingAddressId?: number;
    billingAddress?: Address;
    shippingAddressId?: number;
    shippingAddress?: Address;
    notes?: string | null;
    trackingNumber?: string | null;
    orderDate?: string;
    shippedDate?: string | null;
    deliveredDate?: string | null;
    createdAt?: string | null;
    updatedAt?: string | null;
    isDeleted?: boolean;
    orderItems?: Array<OrderItem> | null;
    payments?: Array<Payment> | null;
}

