/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderConfirmationEmailRequest { 
    toEmail?: string | null;
    orderNumber?: string | null;
    totalAmount?: number;
}

