/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDto } from './orderDto';


export interface OrderItemDto { 
    id?: number;
    orderId?: number;
    order?: OrderDto;
    productId?: number;
    productName?: string | null;
    productSku?: string | null;
    productImageUrl?: string | null;
    quantity?: number;
    unitPrice?: number;
    totalPrice?: number;
    selectedOptions?: string | null;
    createdAt?: string;
}

