/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDto } from './orderDto';


export interface OrderDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: OrderDto;
    timestamp?: string;
    statusCode?: number;
}

