/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDtoPaginatedList } from './orderDtoPaginatedList';


export interface OrderDtoPaginatedListResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: OrderDtoPaginatedList;
    timestamp?: string;
    statusCode?: number;
}

