/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentDetailsDto { 
    paymentMethodId?: number;
    transactionId?: string | null;
    amount: number;
    currency: string;
    gatewayResponse?: string | null;
    notes?: string | null;
}

