/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDto } from './orderDto';


export interface PaymentDto { 
    id?: number;
    orderId?: number;
    order?: OrderDto;
    paymentMethodId?: number;
    paymentMethodName?: string | null;
    transactionId: string;
    status?: string | null;
    paymentStatus?: string | null;
    amount?: number;
    currency?: string | null;
    paymentDate?: string;
    gatewayResponse?: string | null;
    notes?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
}

