/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductSpecificationDto { 
    specificationId?: number;
    specificationName?: string | null;
    value?: string | null;
    displayValue?: string | null;
}

