/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductImage { 
    id?: number;
    productId: number;
    product?: Product;
    imageUrl: string;
    altText?: string | null;
    imageType?: string | null;
    displayOrder?: number;
    isActive?: boolean;
    createdAt?: string;
}

