/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductImageDto } from './productImageDto';


export interface ProductImageDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: ProductImageDto;
    timestamp?: string;
    statusCode?: number;
}

