/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDtoPaginatedList } from './productDtoPaginatedList';


export interface ProductDtoPaginatedListResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: ProductDtoPaginatedList;
    timestamp?: string;
    statusCode?: number;
}

