/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Brand } from './brand';
import { Category } from './category';
import { ProductTag } from './productTag';
import { ProductImage } from './productImage';
import { OrderItem } from './orderItem';
import { Supplier } from './supplier';
import { Review } from './review';
import { Seller } from './seller';
import { ProductSpecification } from './productSpecification';


export interface Product { 
    id?: number;
    name: string;
    description?: string | null;
    shortDescription?: string | null;
    price: number;
    salePrice?: number | null;
    sku?: string | null;
    barcode?: string | null;
    stockQuantity?: number;
    isInStock?: boolean;
    isActive?: boolean;
    isFeatured?: boolean;
    isNew?: boolean;
    viewCount?: number;
    averageRating?: number;
    ratingCount?: number;
    brandId?: number;
    brand?: Brand;
    categoryId?: number | null;
    category?: Category;
    supplierId?: number | null;
    supplier?: Supplier;
    sellerEntityId?: number | null;
    sellerEntity?: Seller;
    createdAt?: string;
    updatedAt?: string | null;
    slug?: string | null;
    images?: Array<ProductImage> | null;
    productTags?: Array<ProductTag> | null;
    productSpecifications?: Array<ProductSpecification> | null;
    reviews?: Array<Review> | null;
    orderItems?: Array<OrderItem> | null;
}

