/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductImageDto { 
    id?: number;
    productId?: number;
    imageUrl: string;
    altText?: string | null;
    imageType?: string | null;
    displayOrder?: number;
    isActive?: boolean;
    createdAt?: string;
}

