/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttributeValue } from './attributeValue';
import { Attribute } from './attribute';
import { Product } from './product';


export interface ProductAttributeValue { 
    id?: number;
    productId?: number;
    product?: Product;
    attributeId?: number;
    attribute?: Attribute;
    attributeValueId?: number | null;
    attributeValue?: AttributeValue;
    textValue?: string | null;
    createdAt?: string;
}

