/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Tag } from './tag';


export interface ProductTag { 
    productId?: number;
    product?: Product;
    tagId?: number;
    tag?: Tag;
    createdAt?: string;
}

