/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Specification } from './specification';


export interface ProductSpecification { 
    productId?: number;
    product?: Product;
    specificationId?: number;
    specification?: Specification;
    value: string;
    displayValue?: string | null;
    createdAt?: string;
}

