/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDto } from './productDto';


export interface ProductDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: ProductDto;
    timestamp?: string;
    statusCode?: number;
}

