/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { QuoteRequest } from './quoteRequest';
import { QuoteStatus } from './quoteStatus';


export interface Quote { 
    id?: number;
    quoteRequestId: number;
    quoteRequest?: QuoteRequest;
    totalPrice: number;
    quoteNotes?: string | null;
    status: QuoteStatus;
    validUntil: string;
    createdAt?: string;
    updatedAt?: string | null;
    acceptedAt?: string | null;
    orderId?: number | null;
    order?: Order;
}
export namespace Quote {
}


