/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { Quote } from './quote';
import { QuoteRequestStatus } from './quoteRequestStatus';
import { Product } from './product';


export interface QuoteRequest { 
    id?: number;
    customerName: string;
    customerEmail: string;
    customerPhone?: string | null;
    companyName?: string | null;
    userId?: string | null;
    user?: ApplicationUser;
    productId?: number;
    product?: Product;
    quantity?: number;
    specialRequirements?: string | null;
    status: QuoteRequestStatus;
    createdAt?: string;
    updatedAt?: string | null;
    responseDate?: string | null;
    adminNotes?: string | null;
    quote?: Quote;
}
export namespace QuoteRequest {
}


