/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RecentOrderDto { 
    orderId?: number;
    customerName?: string | null;
    totalAmount?: number;
    status?: string | null;
    orderDate?: string;
}

