/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterSellerDto { 
    email: string;
    firstName: string;
    lastName: string;
    password: string;
    confirmPassword: string;
    phoneNumber?: string | null;
    shopName: string;
    shopDescription?: string | null;
    businessLicenseNumber?: string | null;
    taxId?: string | null;
    contactEmail: string;
    contactPhone: string;
    address: string;
    city: string;
    state: string;
    postalCode: string;
    country: string;
}

