/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseErrorDto { 
    success?: boolean;
    message?: string | null;
    data?: any | null;
    timestamp?: string;
    statusCode?: number;
}

