/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { Review } from './review';


export interface ReviewReply { 
    id?: number;
    reviewId?: number;
    review?: Review;
    userId: string;
    user?: ApplicationUser;
    replyText?: string | null;
    isActive?: boolean;
    createdAt?: string;
}

