/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './applicationUser';
import { ReviewReply } from './reviewReply';
import { Product } from './product';


export interface Review { 
    id?: number;
    productId?: number;
    product?: Product;
    userId: string;
    user?: ApplicationUser;
    rating?: number;
    title?: string | null;
    comment?: string | null;
    isVerifiedPurchase?: boolean;
    isApproved?: boolean;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string | null;
    helpfulCount?: number;
    notHelpfulCount?: number;
    replies?: Array<ReviewReply> | null;
}

