/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellerDto { 
    id?: number;
    userId?: string | null;
    shopName?: string | null;
    shopDescription?: string | null;
    shopLogoUrl?: string | null;
    businessLicenseNumber?: string | null;
    taxId?: string | null;
    contactEmail?: string | null;
    contactPhone?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    createdAt?: string;
    updatedAt?: string | null;
    lastLoginAt?: string | null;
    isActive?: boolean;
    isVerified?: boolean;
    isPremium?: boolean;
    averageRating?: number;
    totalReviews?: number;
    totalSales?: number;
    totalRevenue?: number;
    totalProducts?: number;
}

