/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SellerDashboardDto } from './sellerDashboardDto';


export interface SellerDashboardDtoResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: SellerDashboardDto;
    timestamp?: string;
    statusCode?: number;
}

