/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellerDashboardDto { 
    totalProducts?: number;
    activeProducts?: number;
    inactiveProducts?: number;
    totalRevenue?: number;
    totalOrders?: number;
    totalSoldItems?: number;
    productsInStock?: number;
    averageOrderValue?: number;
    lastUpdated?: string;
}

