/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SellerDtoPaginatedList } from './sellerDtoPaginatedList';


export interface SellerDtoPaginatedListResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: SellerDtoPaginatedList;
    timestamp?: string;
    statusCode?: number;
}

