/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendEmailRequest { 
    toEmail?: string | null;
    toName?: string | null;
    subject?: string | null;
    body?: string | null;
    isHtml?: boolean | null;
    emailType?: string | null;
    metadata?: { [key: string]: string; } | null;
}

