/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface ShippingTracking { 
    id?: number;
    orderId: number;
    order?: Order;
    status: string;
    description?: string | null;
    location?: string | null;
    carrierName?: string | null;
    carrierCode?: string | null;
    trackingDate?: string;
    estimatedDeliveryDate?: string | null;
    trackingCode?: string | null;
    isDelivered?: boolean;
    sortOrder?: number;
    createdAt?: string | null;
    updatedAt?: string | null;
}

