/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface ShippingMethod { 
    id?: number;
    name: string;
    description?: string | null;
    cost?: number;
    deliveryTime?: string | null;
    supportedCountries?: string | null;
    isActive?: boolean;
    sortOrder?: number;
    createdAt?: string;
    orders?: Array<Order> | null;
}

