/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductTag } from './productTag';


export interface Tag { 
    id?: number;
    name: string;
    slug?: string | null;
    description?: string | null;
    isActive?: boolean;
    createdAt?: string;
    productTags?: Array<ProductTag> | null;
}

