/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuoteRequestStatus } from './quoteRequestStatus';


export interface UpdateQuoteRequestDto { 
    status?: QuoteRequestStatus;
    adminNotes?: string | null;
}
export namespace UpdateQuoteRequestDto {
}


