/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDtoPaginatedList } from './userInfoDtoPaginatedList';


export interface UserInfoDtoPaginatedListResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: UserInfoDtoPaginatedList;
    timestamp?: string;
    statusCode?: number;
}

