/**
 * MISCore Shop API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserInfoDto } from './userInfoDto';


export interface UserInfoDtoIEnumerableResponseSuccessDto { 
    success?: boolean;
    message?: string | null;
    data?: Array<UserInfoDto> | null;
    timestamp?: string;
    statusCode?: number;
}

